<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.22000.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <UseWindowsFormsHighDpiAutoResizing>true</UseWindowsFormsHighDpiAutoResizing>
    <UseWindowsFormsComposition>true</UseWindowsFormsComposition>
    <ApplicationIcon>main.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="main.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="main.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>